name: Deploy to Railway

on:
  workflow_run:
    workflows: ["Docker Build and Push"]
    types:
      - completed
    branches: [ main, master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy to Railway
      uses: railway-app/railway-deploy@v1
      with:
        railway-token: ${{ secrets.RAILWAY_TOKEN }}
        service: ecommerce-app
        detach: true

    - name: Generate deployment summary
      run: |
        echo "## 🚀 Deployed to Railway" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Your application has been deployed to Railway!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Setup Instructions" >> $GITHUB_STEP_SUMMARY
        echo "1. Go to [Railway Dashboard](https://railway.app/dashboard)" >> $GITHUB_STEP_SUMMARY
        echo "2. Create a new project" >> $GITHUB_STEP_SUMMARY
        echo "3. Connect your GitHub repository" >> $GITHUB_STEP_SUMMARY
        echo "4. Add environment variables:" >> $GITHUB_STEP_SUMMARY
        echo "   - \`DB_ROOT_PASSWORD\`" >> $GITHUB_STEP_SUMMARY
        echo "   - \`DB_USER\`" >> $GITHUB_STEP_SUMMARY
        echo "   - \`DB_PASSWORD\`" >> $GITHUB_STEP_SUMMARY
        echo "   - \`JWT_SECRET\`" >> $GITHUB_STEP_SUMMARY
        echo "5. Deploy using the Docker images from GitHub Container Registry" >> $GITHUB_STEP_SUMMARY
