name: Deploy to Render

on:
  workflow_run:
    workflows: ["Docker Build and Push"]
    types:
      - completed
    branches: [ main, master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy to Render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}

    - name: Generate deployment summary
      run: |
        echo "## 🚀 Deployed to Render" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Your application has been deployed to Render!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Setup Instructions" >> $GITHUB_STEP_SUMMARY
        echo "1. Go to [Render Dashboard](https://dashboard.render.com/)" >> $GITHUB_STEP_SUMMARY
        echo "2. Create a new Web Service" >> $GITHUB_STEP_SUMMARY
        echo "3. Connect your GitHub repository" >> $GITHUB_STEP_SUMMARY
        echo "4. Use Docker deployment" >> $GITHUB_STEP_SUMMARY
        echo "5. Set environment variables:" >> $GITHUB_STEP_SUMMARY
        echo "   - \`DB_ROOT_PASSWORD\`" >> $GITHUB_STEP_SUMMARY
        echo "   - \`DB_USER\`" >> $GITHUB_STEP_SUMMARY
        echo "   - \`DB_PASSWORD\`" >> $GITHUB_STEP_SUMMARY
        echo "   - \`JWT_SECRET\`" >> $GITHUB_STEP_SUMMARY
        echo "6. Use the Docker images from GitHub Container Registry" >> $GITHUB_STEP_SUMMARY
